Health/Models/Doctor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Health.Models
{
    public class Doctor
    {
        [Key]
        public int DoctorID { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 2)]
        [Display(Name = "Nombre")]
        public string Name { get; set; }

        [Required]
        [StringLength(120, MinimumLength = 2)]
        [Display(Name = "Apellidos")]
        public string LastName { get; set; }
        
        public int HospitalID { get; set; }

        [Display(Name = "Hospital")]
        public virtual Hospital Hospital { get; set; }

        // collections
        [Display(Name = "Turnos de guardia")]
        public virtual ICollection<Turn> Turns { get; set; }

        [Display(Name = "Consultas")]
        public virtual ICollection<Consult> Consults { get; set; }
    }
}

Health/Controllers/ConsultController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using Health.Models;
using Health.DAL;

namespace Health.Controllers
{
    public class ConsultController : Controller
    {
        private HealthContext db = new HealthContext();

        //
        // GET: /Consult/

        public ActionResult Index()
        {
            var consults = db.Consults.Include(c => c.Doctor).Include(c => c.Pacient);
            return View(consults.ToList());
        }

        //
        // GET: /Consult/Details/5

        public ActionResult Details(int? id = 0)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consult consult = db.Consults.Find(id);
            if (consult == null)
            {
                return HttpNotFound();
            }
            return View(consult);
        }

        //
        // GET: /Consult/Create

        public ActionResult Create()
        {
            ViewBag.DoctorID = new SelectList(db.Doctors, "DoctorID", "Name");
            ViewBag.PacientID = new SelectList(db.Pacients, "PacientID", "Name");
            return View();
        }

        //
        // POST: /Consult/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ConsultDateTime, DoctorID, PacientID")]Consult consult)
        {
            try
            {
                // TODO: invalidate consults at the same date & at the same turn day, how?
                if (ModelState.IsValid)
                {
                    db.Consults.Add(consult);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                // Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Imposible guardar los cambios. Inténtalo de nuevo, y si el problema persiste contacta al administrador de sistema.");
            }

            ViewBag.DoctorID = new SelectList(db.Doctors, "DoctorID", "Name", consult.DoctorID);
            ViewBag.PacientID = new SelectList(db.Pacients, "PacientID", "Name", consult.PacientID);
            return View(consult);
        }

        //
        // GET: /Consult/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Consult consult = db.Consults.Find(id);
            if (consult == null)
            {
                return HttpNotFound();
            }
            ViewBag.DoctorID = new SelectList(db.Doctors, "DoctorID", "Name", consult.DoctorID);
            ViewBag.PacientID = new SelectList(db.Pacients, "PacientID", "Name", consult.PacientID);
            return View(consult);
        }

        //
        // POST: /Consult/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ConsultID, ConsultDateTime, DoctorID, PacientID")]Consult consult)
        {
            try
            {
                // TODO: invalidate consults at the same date & at the same turn day, how?
                if (ModelState.IsValid)
                {
                    db.Entry(consult).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                // Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Imposible guardar los cambios. Inténtalo de nuevo, y si el problema persiste contacta al administrador de sistema.");
            }

            ViewBag.DoctorID = new SelectList(db.Doctors, "DoctorID", "Name", consult.DoctorID);
            ViewBag.PacientID = new SelectList(db.Pacients, "PacientID", "Name", consult.PacientID);
            return View(consult);
        }

        //
        // GET: /Consult/Delete/5

        public ActionResult Delete(int? id = 0, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Falló el borrado. Inténtalo de nuevo, y si el problema persiste contacta al administrador de sistema.";
            }
            Consult consult = db.Consults.Find(id);
            if (consult == null)
            {
                return HttpNotFound();
            }
            return View(consult);
        }

        //
        // POST: /Consult/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Consult consult = db.Consults.Find(id);
                db.Consults.Remove(consult);
                db.SaveChanges();

                /* 
                // another quickly form to delete item
                Consult consultToDelete = new Consult() { ConsultID = id };
                db.Entry(consultToDelete).State = EntityState.Deleted;
                 */
            }
            catch (DataException /* dex */)
            {
                // Log the error (uncomment dex variable name and add a line here to write a log.
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Health/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using Health.Models;
using Health.ViewModels;
using Health.DAL;

namespace Health.Controllers
{
    public class DoctorController : Controller
    {
        private HealthContext db = new HealthContext();

        //
        // GET: /Doctor/

        public ActionResult Index()
        {
            var doctors = db.Doctors.Include(d => d.Hospital);
            return View(doctors.ToList());
        }

        //
        // GET: /Doctor/Details/5

        public ActionResult Details(int? id = 0)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            DoctorViewModel doctorVM = new DoctorViewModel(doctor);
            return View(doctorVM);
        }

        //
        // GET: /Doctor/Create

        public ActionResult Create()
        {
            ViewBag.HospitalID = new SelectList(db.Hospitals, "HospitalID", "Name");
            return View();
        }

        //
        // POST: /Doctor/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name, LastName, HospitalID")]Doctor doctor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Doctors.Add(doctor);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */ )
            {
                // Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Imposible guardar los cambios. Inténtalo de nuevo, y si el problema persiste contacta al administrador de sistema.");
            }

            ViewBag.HospitalID = new SelectList(db.Hospitals, "HospitalID", "Name", doctor.HospitalID);
            return View(doctor);
        }

        //
        // GET: /Doctor/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            ViewBag.HospitalID = new SelectList(db.Hospitals, "HospitalID", "Name", doctor.HospitalID);
            return View(doctor);
        }

        //
        // POST: /Doctor/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DoctorID, Name, LastName, HospitalID")]Doctor doctor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(doctor).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */ )
            {
                // Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Imposible guardar los cambios. Inténtalo de nuevo, y si el problema persiste contacta al administrador de sistema.");
            }

            ViewBag.HospitalID = new SelectList(db.Hospitals, "HospitalID", "Name", doctor.HospitalID);
            return View(doctor);
        }

        //
        // GET: /Doctor/Delete/5

        public ActionResult Delete(int? id = 0, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Falló el borrado. Inténtalo de nuevo, y si el problema persiste contacta al administrador de sistema.";
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        //
        // POST: /Doctor/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Doctor doctor = db.Doctors.Find(id);
                db.Doctors.Remove(doctor);
                db.SaveChanges();

                /* 
                // another quickly form to delete item
                Doctor doctorToDelete = new Doctor() { DoctorID = id };
                db.Entry(doctorToDelete).State = EntityState.Deleted;
                 */
            }
            catch (DataException /* dex */ )
            {
                // Log the error (uncomment dex variable name and add a line here to write a log.
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Health/Controllers/TurnController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using Health.Models;
using Health.DAL;

namespace Health.Controllers
{
    public class TurnController : Controller
    {
        private HealthContext db = new HealthContext();

        //
        // GET: /Turn/

        public ActionResult Index()
        {
            var turns = db.Turns.Include(t => t.Doctor);
            return View(turns.ToList());
        }

        //
        // GET: /Turn/Details/5

        public ActionResult Details(int? id = 0)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turn turn = db.Turns.Find(id);
            if (turn == null)
            {
                return HttpNotFound();
            }
            return View(turn);
        }

        //
        // GET: /Turn/Create

        public ActionResult Create()
        {
            ViewBag.DoctorID = new SelectList(db.Doctors, "DoctorID", "Name");
            return View();
        }

        //
        // POST: /Turn/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TurnDate, DoctorID")]Turn turn)
        {
            try
            {
                // TODO: invalidate turns at the same date, how?
                if (ModelState.IsValid)
                {
                    db.Turns.Add(turn);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                // Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Imposible guardar los cambios. Inténtalo de nuevo, y si el problema persiste contacta al administrador de sistema.");
            }

            ViewBag.DoctorID = new SelectList(db.Doctors, "DoctorID", "Name", turn.DoctorID);
            return View(turn);
        }

        //
        // GET: /Turn/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Turn turn = db.Turns.Find(id);
            if (turn == null)
            {
                return HttpNotFound();
            }
            ViewBag.DoctorID = new SelectList(db.Doctors, "DoctorID", "Name", turn.DoctorID);
            return View(turn);
        }

        //
        // POST: /Turn/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TurnID, TurnDate, DoctorID")]Turn turn)
        {
            try
            {
                // TODO: invalidate turns at the same date, how?
                if (ModelState.IsValid)
                {
                    db.Entry(turn).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                // Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Imposible guardar los cambios. Inténtalo de nuevo, y si el problema persiste contacta al administrador de sistema.");
            }
            ViewBag.DoctorID = new SelectList(db.Doctors, "DoctorID", "Name", turn.DoctorID);
            return View(turn);
        }

        //
        // GET: /Turn/Delete/5

        public ActionResult Delete(int? id = 0, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Falló el borrado. Inténtalo de nuevo, y si el problema persiste contacta al administrador de sistema.";
            }
            Turn turn = db.Turns.Find(id);
            if (turn == null)
            {
                return HttpNotFound();
            }
            return View(turn);
        }

        //
        // POST: /Turn/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Turn turn = db.Turns.Find(id);
                db.Turns.Remove(turn);
                db.SaveChanges();

                /* 
                // another quickly form to delete item
                Turn turnToDelete = new Turn() { TurnID = id };
                db.Entry(turnToDelete).State = EntityState.Deleted;
                 */
            }
            catch (DataException /* dex */)
            {
                // Log the error (uncomment dex variable name and add a line here to write a log.
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Health/Views/Doctor/Create.cshtml
@model Health.Models.Doctor

@{
    ViewBag.Title = "Nuevo doctor";
    ViewBag.Message = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hgroup class="title">
    <h1>@ViewBag.Title </h1>
    <h2>@ViewBag.Message</h2>
</hgroup>
<div class="navbar navbar-default">
    <div class="navbar-left">
        <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink("Listado", "Index")</li>
        </ul>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HospitalID, "Hospital", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HospitalID", String.Empty)
                @Html.ValidationMessageFor(model => model.HospitalID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Health/Views/Doctor/Delete.cshtml
@model Health.Models.Doctor

@{
    ViewBag.Title = "Eliminar doctor";
    ViewBag.Message = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hgroup class="title">
    <h1>@ViewBag.Title </h1>
    <h2>@ViewBag.Message</h2>
</hgroup>
<div class="navbar navbar-default">
    <div class="navbar-left">
        <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink("Listado", "Index")</li>
        </ul>
    </div>
</div>

<p class="error">@ViewBag.ErrorMessage</p>
<h3>¿Está seguro que desea eliminar este elemento?</h3>
<dl class="dl-horizontal">
    <dt>@Html.DisplayNameFor(model => model.Name)</dt>
    <dd>@Html.DisplayFor(model => model.Name)</dd>

    <dt>@Html.DisplayNameFor(model => model.LastName)</dt>
    <dd>@Html.DisplayFor(model => model.LastName)</dd>

    <dt>Hospital</dt>
    <dd>@Html.DisplayFor(model => model.Hospital.Name)</dd>

    <dt>Consultas</dt>
    <dd>@Html.DisplayFor(model => model.Consults.Count)</dd>

    <dt>Turnos</dt>
    <dd>@Html.DisplayFor(model => model.Turns.Count)</dd>
</dl>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Eliminar" class="btn btn-default" />
        </div>
    </div>
}

Health/Views/Doctor/Details.cshtml
@model Health.ViewModels.DoctorViewModel

@{
    ViewBag.Title = "Detalles del doctor";
    ViewBag.Message = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hgroup class="title">
    <h1>@ViewBag.Title </h1>
    <h2>@ViewBag.Message</h2>
</hgroup>
<div class="navbar navbar-default">
    <div class="navbar-left">
        <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink("Editar", "Edit", new { id = Model.Doctor.DoctorID })</li>
            <li>@Html.ActionLink("Eliminar", "Delete", new { id = Model.Doctor.DoctorID })</li>
            <li>@Html.ActionLink("Listado", "Index")</li>
        </ul>
    </div>
</div>
<div>
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(vm => vm.Doctor.Name)</dt>
        <dd>@Html.DisplayFor(vm => vm.Doctor.Name)</dd>

        <dt>@Html.DisplayNameFor(vm => vm.Doctor.LastName)</dt>
        <dd>@Html.DisplayFor(vm => vm.Doctor.LastName)</dd>

        <dt>Hospital</dt>
        <dd>@Html.DisplayFor(vm => vm.Doctor.Hospital.Name)</dd>
    </dl>

    <div class="row">
        <div class="col-md-2 col-md-offset-2">
            <dl class="dl-horizontal">
                <dt>@Html.DisplayNameFor(vm => vm.Doctor.Turns)</dt>
                <dd>@Html.DisplayFor(vm => vm.Doctor.Turns.Count)</dd>
            </dl>
            @if (Model.Doctor.Turns.Count > 0)
            {
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <tr>
                            <th>Fecha</th>
                        </tr>
                        @foreach (var item in Model.Doctor.Turns)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.TurnDate)</td>
                            </tr>
                        }
                    </table>
                </div>
            }
        </div>
        <div class="col-md-5 col-md-offset-2">
            <dl class="dl-horizontal">
                <dt>@Html.DisplayNameFor(vm => vm.Doctor.Consults)</dt>
                <dd>@Html.DisplayFor(vm => vm.Doctor.Consults.Count)</dd>
            </dl>
            @if (Model.Doctor.Consults.Count > 0)
            {
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <tr>
                            <th>Fecha</th>
                            <th>Nombre paciente</th>
                        </tr>
                        @foreach (var item in Model.Doctor.Consults)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.ConsultDateTime)</td>
                                <td>@Html.DisplayFor(modelItem => item.Pacient.Name) @Html.DisplayFor(modelItem => item.Pacient.LastName)</td>
                            </tr>
                        }
                    </table>
                </div>
            }
        </div>
    </div>

    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(vm => vm.Pacients)</dt>
        <dd>@Model.Pacients.Count</dd>
        @if (Model.Pacients.Count > 0)
        {
            <dd>
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <tr>
                            <th>Nombre</th>
                            <th>Apellidos</th>
                        </tr>
                        @foreach (var item in Model.Pacients)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                <td>@Html.DisplayFor(modelItem => item.LastName)</td>
                            </tr>
                        }
                    </table>
                </div>
            </dd>
        }
    </dl>
</div>

Health/Views/Doctor/Edit.cshtml
@model Health.Models.Doctor

@{
    ViewBag.Title = "Edición del doctor";
    ViewBag.Message = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hgroup class="title">
    <h1>@ViewBag.Title </h1>
    <h2>@ViewBag.Message</h2>
</hgroup>
<div class="navbar navbar-default">
    <div class="navbar-left">
        <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink("Agregar consulta", "Create", "Consult")</li>
            <li>@Html.ActionLink("Agregar turno", "Create", "Turn")</li>
            <li>@Html.ActionLink("Eliminar", "Delete", new { id = Model.DoctorID })</li>
            <li>@Html.ActionLink("Listado", "Index")</li>
        </ul>
    </div>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DoctorID)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HospitalID, "Hospital", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HospitalID", String.Empty)
                @Html.ValidationMessageFor(model => model.HospitalID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar cambios" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Health/Views/Doctor/Index.cshtml
@model IEnumerable<Health.Models.Doctor>

@{
    ViewBag.Title = "Doctores";
    ViewBag.Message = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hgroup class="title">
    <h1>@ViewBag.Title </h1>
    <h2>@ViewBag.Message</h2>
</hgroup>
<div class="navbar navbar-default">
    <div class="navbar-left">
        <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink("Agregar nuevo doctor", "Create")</li>
        </ul>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.LastName)</th>
                <th>@Html.DisplayNameFor(model => model.Hospital)</th>
                <th>@Html.DisplayNameFor(model => model.Consults)</th>
                <th>Operaciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.LastName)</td>
                    <td>@Html.DisplayFor(modelItem => item.Hospital.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.Consults.Count)</td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", new { id = item.DoctorID }) |
                        @Html.ActionLink("Detalles", "Details", new { id = item.DoctorID }) |
                        @Html.ActionLink("Eliminar", "Delete", new { id = item.DoctorID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>